apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythia-deployment
  labels:
    app: pythia
spec:
  selector:
    matchLabels:
      app: pythia
  template:
    metadata:
      labels:
        app: pythia
    spec:
      containers:
      - name: pythia
        image: alexanderjackson/pythia:20211222-1539
