[package]
name = "pythia"
version = "0.1.0"
authors = ["Alexander Jackson <alexanderjackson@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
serenity = "0.9"
chrono = "0.4.19"
log = "0.4.11"
pretty_env_logger = "0.4.0"
serde_json = "1.0.60"
serde = "1.0.118"

[dependencies.tokio]
version = "0.3"
features = ["macros"]
